# Generated by Django 5.0.3 on 2024-03-18 23:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('discussion_url', models.CharField(max_length=256, verbose_name='Ссылка на страницу с обсуждением')),
                ('theme', models.CharField(max_length=200, verbose_name='Дата объявления темы и начала приема работ (в 15:00)')),
                ('theme_by', models.CharField(max_length=200, verbose_name='Автор')),
                ('max_in_group', models.PositiveSmallIntegerField(default=50, verbose_name='Максимальное количество произведений в группе')),
                ('max_in_final', models.PositiveSmallIntegerField(default=50, verbose_name='Максимальное количество произведений в финале')),
                ('max_votes', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Количество произведений, за которые голосует участник')),
                ('min_text_size', models.PositiveIntegerField(verbose_name='Минимальная длина произведения')),
                ('max_text_size', models.PositiveIntegerField(verbose_name='Максимальная длина произведения')),
                ('starts', models.DateField(blank=True, null=True, verbose_name='Дата окончания приема работ')),
                ('submission_finishes', models.DateField(blank=True, null=True, verbose_name='Дата окончания приема работ')),
                ('voting_starts', models.DateField(blank=True, null=True, verbose_name='Дата начала первого тура')),
                ('voting_starts_final', models.DateField(blank=True, null=True, verbose_name='Дата окончания первого тура')),
                ('finishes', models.DateField(blank=True, null=True, verbose_name='Дата окончания конкурса')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_coordinator', to=settings.AUTH_USER_MODEL, verbose_name='Координатор')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Конкурс',
                'verbose_name_plural': 'Конкурсы',
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, verbose_name='Имя автора')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('hidden', models.BooleanField(verbose_name='Скрыт')),
                ('group', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Группа')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='litcontest.contest', verbose_name='Конкурс')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Рассказ',
                'verbose_name_plural': 'Рассказы',
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(choices=[(1, 'Начальное'), (2, 'Финальное')], default=1, verbose_name='Этап')),
                ('stars', models.PositiveSmallIntegerField(verbose_name='Оценка')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Голосующий')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='litcontest.story', verbose_name='Рассказ')),
            ],
            options={
                'verbose_name': 'Голосование',
                'verbose_name_plural': 'Голосования',
            },
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('owner', 'story', 'stage'), name='unique_user_vote_combination'),
        ),
    ]
