# Generated by Django 4.2.11 on 2024-03-22 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litcontest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='theme_ext',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Дополнительные условия'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='max_in_final',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальное количество произведений в финале'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='max_in_group',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальное количество произведений в группе'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='max_text_size',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Максимальная длина произведения'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='min_text_size',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальная длина произведения'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='theme',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='theme_by',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тему предложил'),
        ),
        migrations.AlterField(
            model_name='story',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыт'),
        ),
    ]
